---
- name: Deploy graceland
  hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars:
      graceland_web_repo: https://github.com/tessercat/graceland-web.git
      graceland_web_version: dev
  roles:
      - {role: web, tags: [web]}
