---
- name: Packages
  ansible.builtin.apt:
      pkg:
          - php-fpm

- name: Deployment directory
  ansible.builtin.file:
      path: /opt/graceland
      state: directory
      owner: root
      group: root
      mode: 0755

- name: Web directory
  ansible.builtin.file:
      path: /opt/graceland/web
      state: directory
      owner: www-data
      group: www-data
      mode: 0700

- name: Media directory
  ansible.builtin.file:
      path: /opt/graceland/media
      state: directory
      owner: www-data
      group: www-data
      mode: 0700

- name: Web
  become: true
  become_user: www-data
  ansible.builtin.git:
      repo: "{{ graceland_web_repo }}"
      dest: /opt/graceland/web
      version: "{{ graceland_web_version }}"
      force: true

- name: Nginx
  notify:
      - restart graceland nginx service
  ansible.builtin.template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/graceland.conf
      mode: 0644


# Handlers.

- name: Handlers
  ansible.builtin.meta: flush_handlers
