---
- name: Packages
  apt:
      pkg:
        - php-fpm

- name: Deployment directory
  file:
      path: /opt/graceland
      state: directory
      owner: root
      group: root
      mode: 0755

- name: Web directory
  file:
      path: /opt/graceland/web
      state: directory
      owner: www-data
      group: www-data
      mode: 0700

- name: Media directory
  file:
      path: /opt/graceland/media
      state: directory
      owner: www-data
      group: www-data
      mode: 0700

- name: Web
  become: true
  become_user: www-data
  git:
      repo: "{{ web_repo }}"
      dest: /opt/graceland/web
      version: "{{ web_version }}"
      force: true

- name: Nginx
  notify:
      - restart graceland nginx service
  template:
      src: nginx.conf
      dest: /etc/nginx/conf.d/graceland.conf
      mode: 0644


# Handlers.

- name: Handlers
  meta: flush_handlers
